ENV["MEMCACHE_SERVERS"] = ENV["MEMCACHEDCLOUD_SERVERS"] if ENV["MEMCACHEDCLOUD_SERVERS"]
ENV["MEMCACHE_USERNAME"] = ENV["MEMCACHEDCLOUD_USERNAME"] if ENV["MEMCACHEDCLOUD_USERNAME"]
ENV["MEMCACHE_PASSWORD"] = ENV["MEMCACHEDCLOUD_PASSWORD"] if ENV["MEMCACHEDCLOUD_PASSWORD"]
